### ISSUE TITLE
One upvote per user

### ISSUE THREAD

**Issue by the-REAL-beautysleep** [R-J/rating#2]
I seem to be able to upvote or downvote as much as I like. Should it be one per user profile?

**Comment by the-REAL-beautysleep** [comment]
Also, my profile pic sometimes appears over the arrow keys making them unusable

**Comment by R-J** [comment]
IIRC the intention would be that with the Rating.Manage permission there is no limit in up and down votes. That's what I would see as a good way to "manage" a vote. But if also users with only Rating.Add permission can upvote more than one time, than there is obviously an error.

I would need to have a look at the CSS issue. Not sure when I will find the time though, sorry.

**Comment by R-J** [comment]
Looking at [this](https://github.com/R-J/rating/blob/9f3a88cb8378a93d78d88fa6dd5020a06528de5b/RatingPlugin.php#L400-L401), my assumption on how ratings _should_ work was correct.

**Comment by the-REAL-beautysleep** [comment]
Ok that is my mistake for not reading the code documenation
